sonar.projectKey=rodrigo-marques_agora
sonar.organization=rodrigo-marques

sonar.sources=server/src,web/app,web/components,web/hooks,web/services,web/types
sonar.tests=server/src/__tests__,web/e2e

sonar.exclusions=\
  **/coverage/**,\
  **/.next/**,\
  **/node_modules/**,\
  **/dist/**,\
  **/lcov-report/**,\
  **/*.html

sonar.cpd.exclusions=\
  server/src/__tests__/**,\
  web/e2e/**

sonar.javascript.lcov.reportPaths=\
  server/coverage/lcov.info,\
  web/coverage/lcov.info

sonar.typescript.tsconfigPath=server/tsconfig.json
